# 开发环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/donate-admin?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 日志配置
logging:
  level:
    com.mengadmin: debug
    com.baomidou.mybatisplus: error
